name: API Tests

on:
  # 수동 실행
  workflow_dispatch:
  # 테스트/워크플로우 파일 변경 시 자동 실행
  push:
    branches: [ main ]
    paths:
      - "tests/**"
      - ".github/workflows/api-tests.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Run pytest
        # 필요 시 환경변수를 테스트에서 사용할 수 있도록 제공
        env:
          BASE_URL: https://fengshui-api.onrender.com
        run: |
          pytest -q

      
